# fly.toml app configuration file generated for eternalback on 2023-04-30T00:00:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eternalback"
primary_region = "gru"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
